---
title: "Zajęcia z R"
data: 17-12-2019
output: md_document
autor: Ewa Grabska
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wprowadzenie

**R** – język

**Rstudio** – program do języka R

RStudio składa się z kilku podokien i narzędzi: 

*	Konsola (*Console*) – tutaj możesz wpisywać bezpośrednio kod, 

*	Okno środowiska (*Environment*) – wyświetlane tu są wszystkie zapisane w pamięci zmienne, jak i funkcje. Środowisko można zapisać, jak również wczytać. Używając tego okna można również importować dane z zewnątrz oraz przejrzeć historię wpisywanych linii kodu. 

*	Okno z zakładkami – tutaj możemy przeglądać strukturę plików na dysku (*Files*), wyświetlać wykresy (*Plots*), przeglądać zainstalowane pakietu (*Packages*), szukać pomocy na temat funkcji z pakietów (*Help*). 

*	W R najczęściej chcemy pisać skrypty składające się z wielu linii, które następnie będziemy wykonywać. Do otwarcia nowego skryptu służy ikona Add R Script lub kombinacja klawiszy Ctrl+Shift+N. 

[Podstawy R - cheat sheet](github.com/rstudio/cheatsheets/raw/master/base-r.pdf)

Funkcje – zazwyczaj skonstruowane w sposób:

nazwa_funkcji(x, y, …)

* x – dane wejściowe
* y – dalsze argumenty, które mogą być 
Na przykład w funkcji [`read.csv()`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/read.table.html), która służy do wczytywania danych w formacie csv:

`read.csv(file, header = TRUE, sep = ",", quote = "\"", dec = ".", fill = TRUE, comment.char = "", ...)`

Wynik działania danej funkcji możemy przypisać do zmiennej:
	`dane = read.csv(…)`

Typy obiektów w R:

*	Wektory 
*	Macierze
*	Listy
*	Tekst
*	Ramki danych (**data frames**)

Wczytywanie bazy danych - najczęściej w formacie .csv > obiekt typu data frame
Po wczytaniu danych warto sprawdzić czy wszystko z nimi w porządku, np. uzywając str() lub summary()
  `str(dane)`
  `summary(dane)`

Po wywołaniu fukncji str() zobaczymy strukturę każdej z kolumn. Pamiętaj, że aby przeprowadzac dalsze przetowrzenia na liczbach odpowiednie kolumny muszą mięć odpowiednie formaty liczbowe - czyli **int** lub **num**
Dostęp do poszczególne kolumn - możemy użyć znaku $ czyli:

  `dane$nachylenie` 
lub
  
  `dane[,4]`

Help 

Pakiety – instalacja i wczytywanie
W R dostępnych jest wiele funkcji „bazowych”, jedną z nich jest `read.csv`. Istenieje jednak niezliczona ilość funkcji bardziej złożonych i stworzonych do specyfinczych zadań. Są one zawarte w pakietach (packages). Aby wykorzystać funkcję z jakiegoś pakietu należy najpierw go zainstalować (raz), następnie wczytać (każdorazowo przy nowym projekcie). Służą do tego funckje:

`install.packages(„nazwa_pakietu”)`

`library(nazwa_pakietu)`

Instalować pakiety można również wchodząc w zakładkę Packages.


## Analizy statystyczne w R

* Korelacja
* Współczynnik korelacji liniowej Pearsona
* Współczynnik korelacji rang Spearmana
* Regresja, modele regresji
* Prosta regresja liniowa
* Regresja wieloraka

Proste wykresy mozna tworzyć za pomocą funckji `plot()`




## Wizualizacje w R
Wykorzystamy pakiet ggplot2. 




